### ISSUE TITLE
当_DIFF 比较对象中包含LocalDateTime时 抛出java.lang.NullPointerException: null  version：3.0.3

### ISSUE THREAD

**Issue by 0xtoolkit** [mouzt/mzt-biz-log#111]
java.lang.NullPointerException: null
	at com.mzt.logapi.starter.diff.DefaultDiffItemsToLogContentService.getFunctionValue(DefaultDiffItemsToLogContentService.java:190)
	at com.mzt.logapi.starter.diff.DefaultDiffItemsToLogContentService.getDiffLogContent(DefaultDiffItemsToLogContentService.java:152)
	at com.mzt.logapi.starter.diff.DefaultDiffItemsToLogContentService.generateAllFieldLog(DefaultDiffItemsToLogContentService.java:78)
	at com.mzt.logapi.starter.diff.DefaultDiffItemsToLogContentService.lambda$toLogContent$0(DefaultDiffItemsToLogContentService.java:50)
	at de.danielbechler.diff.node.DiffNode.visit(DiffNode.java:414)
	at de.danielbechler.diff.node.DiffNode.visit(DiffNode.java:403)
	at de.danielbechler.diff.node.DiffNode.visitChildren(DiffNode.java:441)
	at de.danielbechler.diff.node.DiffNode.visit(DiffNode.java:422)
	at de.danielbechler.diff.node.DiffNode.visit(DiffNode.java:403)
	at de.danielbechler.diff.node.DiffNode.visitChildren(DiffNode.java:441)
	at de.danielbechler.diff.node.DiffNode.visit(DiffNode.java:422)
	at de.danielbechler.diff.node.DiffNode.visit(DiffNode.java:403)

DiffNode Map读取时会获取到LocalDateTime对象中的nano。该值为空导致抛出空指针。
DIffLogIgnore属性由于判断逻辑是在DiffNode读取之后，且并不影响children读取，故加该注解无效。

**Comment by mouzt** [comment]
3.0.4 版本已经修复
